# Generated by Django 3.0.6 on 2020-06-10 21:53

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comments',
            field=django_mysql.models.ListTextField(models.CharField(max_length=1024), blank=True, size=100),
        ),
        migrations.AddField(
            model_name='article',
            name='imageurl',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='article',
            name='numlikes',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
