# Generated by Django 3.0.6 on 2020-06-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200610_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='imagecaption',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='article',
            name='subtitle',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
