# Generated by Django 3.0.6 on 2020-06-11 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200610_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='imageurl',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
