# Generated by Django 3.0.7 on 2020-06-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200612_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='imageurl',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
