# Generated by Django 3.0.7 on 2020-06-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_author_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='author',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='author',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
