# Generated by Django 3.0.7 on 2020-06-25 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200625_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='mainauthor',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='primary_articles', to='blog.Author'),
            preserve_default=False,
        ),
    ]
