# Generated by Django 3.0.7 on 2020-06-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_article_mainauthor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='authors',
        ),
        migrations.AddField(
            model_name='article',
            name='other_authors',
            field=models.ManyToManyField(blank=True, to='blog.Author'),
        ),
    ]
