# Generated by Django 3.0.6 on 2020-06-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechPeCharcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('youtubelink', models.CharField(max_length=256)),
            ],
        ),
    ]
