# Generated by Django 3.0.6 on 2020-06-10 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_techpecharchaepisodes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TechPeCharcha',
        ),
    ]
