# Generated by Django 3.0.6 on 2020-06-10 17:01

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_delete_techpecharcha'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicSpeakingEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('youtubelink', models.CharField(blank=True, default='', max_length=256)),
                ('images', django_mysql.models.ListTextField(models.CharField(max_length=512), size=15)),
                ('staticimages', django_mysql.models.ListTextField(models.CharField(max_length=512), size=10)),
            ],
        ),
    ]
