# Generated by Django 3.0.6 on 2020-06-10 17:05

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_publicspeakingevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicspeakingevents',
            name='images',
            field=django_mysql.models.ListTextField(models.CharField(max_length=512), blank=True, size=15),
        ),
        migrations.AlterField(
            model_name='publicspeakingevents',
            name='staticimages',
            field=django_mysql.models.ListTextField(models.CharField(max_length=512), blank=True, size=10),
        ),
    ]
