# Generated by Django 3.0.7 on 2020-06-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('youtubelink', models.CharField(max_length=256)),
            ],
        ),
    ]
