# Generated by Django 3.0.7 on 2020-06-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_youtubelinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubelinks',
            name='title',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
